### ISSUE TITLE
Restart transient build failures

### ISSUE THREAD

**Issue by wilzbach** [dlang-bots/dlang-bot#122]
It happens quite often that we see "random" build failures due to network errors, concurrency etc.

While in theory we should try to tackle the root of the problem, a intermediate solution would be to allow the bot to restart these builds.

In particular:

- Travis (e.g. dmd, DUB, Vibe.d) -> lots of network errors when installing DMD and sometimes even Travis errors with non-starting jobs
- Project-Tester -> lots of random errors due to the DUB registry

**Comment by MartinNowak** [comment]
Fix the problems, don't automate the workarounds.
