### ISSUE TITLE
Auto-restart all CI builds when a PR has been merged

### ISSUE THREAD

**Issue by wilzbach** [dlang-bots/dlang-bot#132]
As many commercial CIs (Travis, CircleCi, ...) don't restart the builds after a commits have been pushed to the targeting branch, it's possible to accidentally merge non-passing PRs.

A simple solution would be to restart the last CI build for all pending PRs for these providers on a merge event.
For performance only latest X (e.g. 50) PRs (sorted by the last update timestamp) could be triggered.
Of course only PRs targetting the modified branch need to be restarted (i.e. on a commit to `stable` there's no need to restart a PR targetting master).

Currently the dlang-bot doesn't receive commit hooks, but at least for the repos on which this feature is enabled, it would probably more failure-prove than the PR merge event (though that will work as well).
Lastly for example on Phobos CircleCi runtimes are moderate < 10 mins and 4x parallelism is available, so restarting PRs here is a possibility whereas Travis at the dmd repo is usually pretty clogged already.

**Comment by MartinNowak** [comment]
Nope, this mode of testing has quadratic behavior, and while strictly speaking being more correct than only testing the branch head, situations where new commits (after first test) on master cause semantic code conflicts (new bugs) in the PR without also causing merge conflicts (text collisions) are too rare to really bother. And once merged they get tested on master anyhow and can trivially be reverted.
