### ISSUE TITLE
Use GitHub's new `author_association` for the Bot's info message

### ISSUE THREAD

**Issue by wilzbach** [dlang-bots/dlang-bot#154]
Currently we query via another API call whether a user is part of the respective GitHub team.
However, there's a new field for pull request: `author_association` (e.g. "CONTRIBUTOR") which would save this additional API call.

**Comment by MartinNowak** [comment]
Are we short on GH API calls?

**Comment by wilzbach** [comment]
Now just something I saw that GH sends since a couple of months. If we are ever short on API calls, we should simply introduce a caching layer.
