### ISSUE TITLE
Automatically assign reviewers

### ISSUE THREAD

**Issue by wilzbach** [dlang-bots/dlang-bot#31]
Our first experiment with the mention bot didn't work that well, but we should look into learning from it and rebooting the idea.

Some learned lessons:

- use interpolation of the time changed (especially braddr was mentioned a lot because I think he initialized the git repo back in the old days)
- wait for X days until assigning reviewers as someone might have already picked up the PR or even merged it
- always assign more than one reviewer
- use the new review assign feature (I think there's [no API yet](https://github.com/facebook/mention-bot/issues/192))
- don't mention reviewers that don't have write access
- include the last activity on a dlang repo in the evaluation (workflow tend to differs, but generally people have their "active" phases)
- don't post a separate comment

**Comment by wilzbach** [comment]
Alternatively we could maintain a list of GitHub handels publicly on GitHub (e. g. a simple text file for each repository), so that everyone can ask to add/remove himself on his own.

**Comment by wilzbach** [comment]
I found this interesting & simple concept at [kubernets](https://github.com/kubernetes/contrib) as it allows to include non-maintainers to be part of the review process:

> In order for your PR to get merged, it must have the both `lgtm` AND `approved` labels.  When you open a PR, the k8s-merge-bot will automatically assign a reviewer from the `OWNERS` files.  Once assigned, the reviewer can then comment `/lgtm`, which will add the `lgtm` label, or if he/she has permission, the reviewer can add the label directly.
> Each file modified in the PR will also need to be approved by an approver from its `OWNERS` file or an approver in a parent directory's `OWNERS` file.  A file is approved when the approver comments `/approve`, and it is unapproved if an approver comments `/approve cancel`.  When all files have been approved, the `approved` label will automatically be added by the k8s-merge-bot and the PR will be added to the submit-queue to be merged.

**Comment by MartinNowak** [comment]
Seems to be done by GH nowadays.
