### ISSUE TITLE
put auto-merge at the bottom of the labels list

### ISSUE THREAD

**Issue by wilzbach** [dlang-bots/dlang-bot#33]
>>>UI-wise, I like the idea of having the merge toggle in github. But I'm a bit concerned about accidentally merging because you clicked the wrong label. Definitely there needs to be a delay in merging (probably at least 20 seconds).

>> You could also accidentally hit the "green" merge button - it would be immediate as well.

>That's not next to the "allocator" label button :wink:
> Hm... a crude idea on that -- the labels seem listed alphabetically, you could make the label "ZZZ auto-merge" so they are always at the bottom.

or e.g. `{automerge}`

CC @schveiugy (from https://github.com/dlang/phobos/pull/4967)

**Comment by MartinNowak** [comment]
Adding a label is already a 2-step process, select and confirm, so I don't think this is going to be a big issue.
But using some namesspace prefix such as `pr:` or `z:` would be fine.

**Comment by MartinNowak** [comment]
Accidentally merging something wouldn't be such a huge issue either, just revert it right away.
Let's see if it's a practical problem.

**Comment by wilzbach** [comment]
Doesn't seem to be an issue for anyone -> closing.
