### ISSUE TITLE
Automatically add the "bugfix" label if issue references are detected

### ISSUE THREAD

**Issue by wilzbach** [dlang-bots/dlang-bot#38]
Should be pretty trivial and could help a bit to filter for pending fixes prior the merge window. 

It might be more complicated to automatically remove the label and I guess this won't happen often, so I would go with the simplest case for now.

**Comment by MartinNowak** [comment]
Sounds good, we have bugfix for phobos, and [regression](https://github.com/dlang/dmd/labels/Regression) for dmd. Could use the same labels across all repos.

**Comment by wilzbach** [comment]
> Sounds good

See #39 for the implementation ;-)

> we have bugfix for phobos, and regression for dmd. Could use the same labels across all repos.

+1 - I don't mind which one you pick.
