### ISSUE TITLE
Should the dlang-bot automatically post new regressions as new Trello cards into the inbox?

### ISSUE THREAD

**Issue by wilzbach** [dlang-bots/dlang-bot#40]
Apparently it's possible to provide custom hooks for Bugzilla as well (e.g. https://www.bugzilla.org/docs/4.4/en/html/api/Bugzilla/Hook.html), but it seems a bit more complicated 

Otherwise a simple cron job that queries the bugzilla API for new regression every X hours should work as well.

**Comment by MartinNowak** [comment]
No, similar to the assignment, automatically scheduling work that can't be done b/c we're lacking resources doesn't help.
Querying for regressions is trivial enough https://issues.dlang.org/buglist.cgi?bug_severity=regression&order=Importance&query_format=advanced&resolution=---.
