### ISSUE TITLE
Trigger a warning when a PR gets unmergeable

### ISSUE THREAD

**Issue by wilzbach** [dlang-bots/dlang-bot#43]
Could be helpful:

![image](https://cloud.githubusercontent.com/assets/4370550/22858883/555cad02-f0ca-11e6-836d-481ad89eae2b.png)

(seen [here](https://github.com/servo/servo/pull/15368#issuecomment-277317077))

However, I am not sure how noisy this would be become

**Comment by nox** [comment]
@wilzbach As a Servo developer, I can say it's not that noisy, and quite useful. Also it can offer people [some bragging points sometimes](https://twitter.com/nokusu/status/735048635059146754), each of these referenced pull requests were bitrot all at once with one of mine when it landed. :)

**Comment by wilzbach** [comment]
> @wilzbach As a Servo developer, I can say it's not that noisy, and quite useful.

I think if we start this by just labelling unmergable PRs, this would already be an excellent step. Whether we then send the comment (or personal emails) or not, is than "merely" philosophical (or political).
In case you are interested, I submitted a PR of the first iteration of such a feature here (https://github.com/dlang-bots/dlang-bot/issues/52), so maybe we can seen the bot reporting this in the near future ;-)

**Comment by wilzbach** [comment]
> I submitted a PR of the first iteration of such a feature here (#52), so maybe we can seen the bot reporting this in the near future ;-)

This is deployed and we now (experimentally) label PRs as "needs rebase" once a day.

See e.g. https://github.com/dlang/phobos/pulls?q=is%3Aopen+is%3Apr+label%3A%22needs+rebase%22

Sending out notifications would be a rather trivial step on top of that, but I am still afraid that it's too spammy. Maybe we can add a simple mechanism for a user to opt-out?

**Comment by MartinNowak** [comment]
We have a needs rebase label nowadays.

**Comment by MartinNowak** [comment]
Regarding mail @wilzbach, it seems we'd need a user preference for E-Mail heavy workflows.
Personally I've almost abandoned E-Mail, so I can not really decide what's useful or not, when your work is centered around it. It's just that we also have to consider the visual cluttering in the important comments.
A custom Webextension to make dlang-bot comments less present would work for me, but hardly helps other people. Already have a userContent.css for github to make the news list opaque.
```css
@-moz-document url('https://github.com/') {
    div.news { opacity: 0.1 !important; }
}
```
