### ISSUE TITLE
Let the bot help with release process 

### ISSUE THREAD

**Issue by wilzbach** [dlang-bots/dlang-bot#48]
@MartinNowak I am not sure how much a bot can help you with the release process - in other words: what is taking up time? 

Anyhow, here are a couple of ideas that come to my mind:
- automatically open a PR to "master" from "stable"  after a merged regression fix (or every X days)
- update released version (Wikipedia, DWiki) - though I guess that's better than via a one-off script
- automatically warn on PRs with a linked milestone when only X days remain until the targeted date

**Comment by MartinNowak** [comment]
Not much, most is scripted already.
https://wiki.dlang.org/DMD_Release_Building
https//gist.github.com/a471fe7ddbfeef205cdf04c93a94c6d0
