### ISSUE TITLE
Use Markdown instead of HTML in greeter message

### ISSUE THREAD

**Issue by CyberShadow** [dlang-bots/dlang-bot#92]
After making a PR, the email I get from GitHub with @dlang-bot's automatic comment looks like this:

![](https://dump.thecybershadow.net/54c55d6eeff5b8241eb01b95cb4d27bb/08%3A04%3A07-upload.png)

I suggest using Markdown instead of HTML unless absolutely necessary, so that the email appears more readable in email clients configured or limited to displaying text/plain parts over text/html.

**Comment by wilzbach** [comment]
Hmm, this is due to https://github.com/dlang-bots/dlang-bot/pull/89 as AFAICT Markdown will always render line breaks as new lines in the HTML.

**Comment by CyberShadow** [comment]
Can you post some example Markdown that doesn't work, and a description of what it should look like?

**Comment by CyberShadow** [comment]
The comment in question, looks identical to me:

---

# HTML

Thanks for your pull request, @CyberShadow!

### Bugzilla references

Your PR doesn't reference any Bugzilla issue.
<p>
If your PR contains non-trivial changes, please
<a href="https://github.com/dlang-bots/dlang-bot#automated-references">reference a Bugzilla issue</a>
or create a <a href="https://github.com/dlang/dlang.org/blob/master/changelog">manual changelog</a>.
</p>

---

# Markdown

Thanks for your pull request, @CyberShadow!

### Bugzilla references

Your PR doesn't reference any Bugzilla issue.

If your PR contains non-trivial changes, please [reference a Bugzilla issue](https://github.com/dlang-bots/dlang-bot#automated-references) or create a [manual changelog](https://github.com/dlang/dlang.org/blob/master/changelog).

**Comment by wilzbach** [comment]
> Can you post some example Markdown that doesn't work, and a description of what it should look like?

AAAA
BBB <- `<br>` inserted here


Well we could always just don't care about the 120 line length and dump the raw output in one long line ...

**Comment by wilzbach** [comment]
> The comment in question, looks identical to me:

It's not about Markdown rendering per se, it's that a line break in Markdown will result in a `<br>` and thus one needs to use one, very long line.

**Comment by CyberShadow** [comment]
> It's not about Markdown rendering per se, it's that a line break in Markdown will result in a `<br>` and thus one needs to use one, very long line.

When does that become a problem?

**Comment by CyberShadow** [comment]
Wait, is this just about the line length in the bot's *source code*?

Just use string concatenation then, sheesh.

**Comment by wilzbach** [comment]
> Wait, is this just about the line length in the bot's source code?

Yes.

Anyhow, I didn't consider the HTML as a big problem, sorry -> https://github.com/dlang-bots/dlang-bot/pull/93
