### ISSUE TITLE
"needs work" should ignore CodeCov

### ISSUE THREAD

**Issue by wilzbach** [dlang-bots/dlang-bot#98]
![image](https://user-images.githubusercontent.com/4370550/27569664-0c6619c8-5af9-11e7-9526-5d1f4bcdce9f.png)

(or at least reduce it to a single CI)

**Comment by MartinNowak** [comment]
As usual, reliability trumps ignorance when it comes to CIs.

**Comment by wilzbach** [comment]
1) CodeCov isn't counted as a failing CI - https://github.com/dlang-bots/dlang-bot/blob/master/source/dlangbot/cron.d#L146
2) CodeCov can't fail anymore as we use `informational: true` and `threshold: 0`

-> this isn't a problem anymore
