### ISSUE TITLE
Stalled: look at commits too

### ISSUE THREAD

**Issue by wilzbach** [dlang-bots/dlang-bot#99]
`updatedAt` of the PR gets updated with adding a label and we currently just look at the last comment.
In some cases looking at `updatedAt` of the commits would be helpful as well:

![image](https://user-images.githubusercontent.com/4370550/27569705-47a2f70e-5af9-11e7-8ff1-7ca600f9207d.png)

https://api.github.com/repos/dlang/phobos/pulls/5004

**Comment by MartinNowak** [comment]
So this is about removing the stalled label when new commits are pushed? Don't we already get the hook and do that?

**Comment by wilzbach** [comment]
Yes we already do that, but in the cron job: https://github.com/dlang-bots/dlang-bot/blob/master/source/dlangbot/cron.d#L60
